export { default as PIconInstagram } from '../components/icons/p-icon-instagram/PIconInstagram.vue'
export { default as PIconFacebook } from '../components/icons/p-icon-facebook/PIconFacebook.vue'
export { default as PIconTwitter } from '../components/icons/p-icon-twitter/PIconTwitter.vue'
export { default as PIconPostanu } from '../components/icons/p-icon-postanu/PIconPostanu.vue'
export { default as PIconVK } from '../components/icons/p-icon-vk/PIconVK.vue'
export { default as PIconArrowNorthEast } from '../components/icons/p-icon-arrow-north-east/PIconArrowNorthEast.vue'
export { default as PIconClose } from '../components/icons/p-icon-close/PIconClose.vue'
export { default as PIconPlus } from '../components/icons/p-icon-plus/PIconPlus.vue'
