export { default as PEditorText } from '../components/editor/p-editor-text/PEditorText.vue'
export { default as PEditorTime } from '../components/editor/p-editor-time/PEditorTime.vue'
export { default as PEditorClock } from '../components/editor/p-editor-clock/PEditorClock.vue'
export { default as PEditorPage } from '../components/editor/p-editor-page/PEditorPage.vue'
export { default as PEditorPageList } from '../components/editor/p-editor-page-list/PEditorPageList.vue'
export { default as PEditorAttachments } from '../components/editor/p-editor-attachments/PEditorAttachments.vue'
