export { default as PEditorText } from '../components/p-editor-text/PEditorText.vue'
export { default as PEditorTime } from '../components/p-editor-time/PEditorTime.vue'
export { default as PEditorClock } from '../components/p-editor-clock/PEditorClock.vue'
export { default as PEditorPages } from '../components/p-editor-pages/PEditorPages.vue'
export { default as PEditorAttachments } from '../components/p-editor-attachments/PEditorAttachments.vue'
